import type { NextPage } from 'next'
import Head from 'next/head'
import MainContainer from '../components/MainContainer'

const Home: NextPage = () => {
  return (
    <div style={{
      backgroundColor: '#fafafa',
      minHeight: '100vh',
      maxHeight: 'fit-content'
    }}>
      <Head>
        <title>Country Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer />
    </div>
  )
}

export default Home
